### ISSUE TITLE
Add more testthat tests

### ISSUE THREAD

**Issue by WillemSleegers** [WillemSleegers/tidystats#1]
Add (more) testthat tests for:

- [x] tidy_stats_to_data_frame.R
- [x] emmeans

**Comment by Scott-S-Hannah** [comment]
Hi Willem, 

Sorry for the delay!

I previously mentioned that it would be a nice addition if tidystats could work with the `emmeans` package. 

For instance, I tend to run my ANOVA models with the `afex` package and specify this in my emmeans call with the IV of interest. 

```r
library(afex)
library(emmeans)

anova_mod <- afex::aov_ez(id = "id", dv = "value", data = obk.long, between = "treatment", within = c("phase", "hour"))

anova_emm <- emmeans::emmeans(anova_mod, ~ phase)

results <- pairs(anova_emm)

results
```

 I would then tend to report these as a t-test—i.e. Mdiff = -0.621, SE = 0.306, t(26) = 2.033, p = .1242

Do you think this would be possible?

Many thanks, 
Scott

**Comment by WillemSleegers** [comment]
Definitely possible; I've already started writing some code for it. Probably will have something done this weekend!

**Comment by Scott-S-Hannah** [comment]
I wish I had your level of productivity, @WillemSleegers! Thanking you.
