### ISSUE TITLE
Cronbach's alpha?

### ISSUE THREAD

**Issue by jatx50** [WillemSleegers/tidystats#12]
I see that the `psych` package's alpha used to be supported in v0.3 ([docs here](https://www.rdocumentation.org/packages/tidystats/versions/0.3/topics/tidy_stats.psych)), but seems latest `tidystats` version doesn't support it? Any workarounds or other tidystats-compatible packages to use for calculating alpha?

**Comment by WillemSleegers** [comment]
Hey @rinkjames; it's possible I dropped that feature while recoding various aspects of tidystats. I'll take a look tomorrow or so to see if I can add it back. You can then install the development version of tidystats to access the new support.

**Comment by WillemSleegers** [comment]
So, the dev version of `tidystats` has support for the `alpha` function of the `psych` package! You can install the version with `devtools::install_github("willemsleegers/tidystats@0.5.1")`. The Word add-in also can read this output, so you can use that to report the statistics. =) Let me know if this doesn't work for you or if you have any other feedback!

**Comment by jatx50** [comment]
Looks like it works great. Thanks!
