### ISSUE TITLE
Vignette/Readme could explain more about what the goal is

### ISSUE THREAD

**Issue by daaronr** [WillemSleegers/tidystats#17]
It's not clear to me what I might do with the output of this ... a .json file. Maybe give some examples or links to 'what I can do with that'?

**Comment by WillemSleegers** [comment]
Did you read the README?

Specifically, [this](https://github.com/WillemSleegers/tidystats/tree/master#reporting-statistics) section.

**Comment by daaronr** [comment]
Yeah it says:

> This results is a .json file that contains all the statistics from the three models. If you want to see what this file looks like, you can inspect it [here](https://github.com/WillemSleegers/tidystats/blob/master/inst/results.json).

> Reporting statistics If you want to report the statistics in a manuscript, you can do so with a Word add-in that is currently in development [here](https://github.com/WillemSleegers/tidystats-Word-add-in).

So is the 'main goal' or 'use case' to report the statistics in a manuscript with the word add-in? If so, maybe that should be made clearer? 

Otherwise, not everyone knows what to do with a .json file, I think

**Comment by WillemSleegers** [comment]
That's one of the use cases. The other use case is simply using the file itself to store statistics.

I suppose I can mention the add-ins more prominently at the start of the README.
