### ISSUE TITLE
Support for emmeans functions

### ISSUE THREAD

**Issue by gasparl** [WillemSleegers/tidystats#25]
I began adding support for the `emmeans` package. Here, everything revolves around the `emmeans::emmeans` function, so this should be rather simple. 

However, one thing to note is that, same as with [`marginalmeans`](https://github.com/WillemSleegers/tidystats/issues/23#issuecomment-1159993076), only the `summary` outputs seem meaningful. In fact, the `emmeans` package itself uses the `print`/`show`/`tidy` methods of `emmeans::emmeans` output in a way that they first pass the output to `summary`, and only then print these summary results. For now, I only implement `tidy_stats` methods that take the `summary` output, such as `summary(emmeans())`. In case of plain `emmeans()`, I could also imitate the way of first passing it to `summary()` internally, but I think that might be a bit confusing for users, so I'd just omit that option and leave it to users to explicitly use either `summary()` or grab the `data.frame` or whatever else they want to report from the original `emmeans()` output.

**Comment by WillemSleegers** [comment]
I would just run `summary()` internally. We also already do that for regression.

**Comment by gasparl** [comment]
Okay sure, I'll do that then.

**Comment by gasparl** [comment]
This is done. (With support for `emmeans`'s `emmeans()`, `summary()`, `confint()`, `test()`, `contrast()`, `mvcontrast()`, `eff_size()`, `emtrends()`, `joint_tests()`, `ref_grid()`.)

**Comment by WillemSleegers** [comment]
Sweet!

**Comment by WillemSleegers** [comment]
I have redone support for `emmeans` and should support all functions now.
