### ISSUE TITLE
Add support for emmeans

### ISSUE THREAD

**Issue by WillemSleegers** [WillemSleegers/tidystats#3]
Add support for functions in the emmeans package.

**Comment by WillemSleegers** [comment]
#1

**Comment by WillemSleegers** [comment]
> Hi Willem,
> 
> Sorry for the delay!
> 
> I previously mentioned that it would be a nice addition if tidystats could work with the `emmeans` package.
> 
> For instance, I tend to run my ANOVA models with the `afex` package and specify this in my emmeans call with the IV of interest.
> 
> ```r
> library(afex)
> library(emmeans)
> 
> anova_mod <- afex::aov_ez(id = "id", dv = "value", data = obk.long, between = "treatment", within = c("phase", "hour"))
> 
> anova_emm <- emmeans::emmeans(anova_mod, ~ phase)
> 
> results <- pairs(anova_emm)
> 
> results
> ```
> 
> I would then tend to report these as a t-test—i.e. Mdiff = -0.621, SE = 0.306, t(26) = 2.033, p = .1242
> 
> Do you think this would be possible?
> 
> Many thanks,
> Scott

Moved your post here, Scott. (I created the other issue for code-testing, not statistical tests; my bad!)

**Comment by WillemSleegers** [comment]
@Scott-S-Hannah I added support for emmeans in the dev version of tidystats. I ran a few tests, but I'm not sure I got all edge-cases. 

Please take it out for a spin, and let me know if there's a problem!

**Comment by Scott-S-Hannah** [comment]
Fantastic @WillemSleegers ! Will give this a spin this week, thanks.

**Comment by WillemSleegers** [comment]
Hey @Scott-S-Hannah, did you have a chance to test it out?

**Comment by Scott-S-Hannah** [comment]
Sorry for the radio silence. It has been working nicely! I've been using it for reporting contrasts in my thesis and it's a huge help!Will continue to use and keep you posted. Thanks Willem.

**Comment by WillemSleegers** [comment]
Sweet, glad to hear it! I'll close this issue for now, but if there's an issue, feel free to re-open it or post a new issue.
