### ISSUE TITLE
emmeans parsing issue?

### ISSUE THREAD

**Issue by Scott-S-Hannah** [WillemSleegers/tidystats#8]
Hi Willem, 

Sorry for the vague issue title, I wasn't sure how to best describe it. 

There seems to be some parsing issue with `emmGrid` objects; correct me if I'm wrong.

I've included a small example below (sorry if it's a bit messy). The json file only seems to catch the _df_ and _SE_.

```
library(afex)
library(tidystats)

participant <- rep(seq(1, 10), each = 21)
condition <- rep(c("cond_1", "cond_2", "cond_3"), times = 70)
time <- rep(seq(0, 30, 5), each = 3, times = 10)
response <- rnorm(n = 210, mean = c(1.1, 1.2, 1.3), sd = 0.1)

df <- data.frame(participant = factor(participant),
                 time = factor(time),
                 condition = factor(condition),
                 response)

model <- mixed(response ~ condition * time +
                 (condition | participant),
               df)

emm_results <- emmeans(model, "condition", by = "time") %>% 
  contrast("pairwise")

results <- list()

results <- results %>% 
  add_stats(emm_results)

write_stats(results, "test_results.json")
``` 

Many thanks,
Scott

**Comment by WillemSleegers** [comment]
Hey Scott,

I totally missed this issue, sorry!

I think I fixed it now. You can install the new version with the following code:
`devtools::install_github("willemsleegers/tidystats@0.5.1")`

Please let me know if this fixed it or not. =)

**Comment by Scott-S-Hannah** [comment]
Hi Willem, 

No problem at all 😄 . 

That works perfectly!

Thanks.
